[package]
name = "jsompiler_lexer"
version = "0.1.0"
edition = "2024"
description = "Lexer for JavaScript"
license = "MIT"
repository = "https://github.com/abhiyandhakal/jsompiler"
readme = "../../README.md"

[dependencies]
lazy_static = "1.5.0"
jsompiler_common = { path = "../jsompiler_common" }
